#Perform diffrent arithmatic operations on numbers in python. (Understanding vectors, Metrices, Solving problems in Python)

###Create a Horizontal Vector

In [1]:
import numpy as np

H_Vector = np.array([1,2,3])
print("Horizontal Vector is: ",H_Vector)

Horizontal Vector is:  [1 2 3]


###Create a vertical Vector

In [6]:
import numpy as np

V_Vector = np.array([[10],[20],[30]])
print("Vertical Vector is: \n",V_Vector)

Vertical Vector is: 
 [[10]
 [20]
 [30]]


###Perform an addition operation on python vectors

In [5]:
addition = H_Vector + V_Vector
print("Addition of two vectors is: \n ",addition)

Addition of two vectors is: 
  [[11 12 13]
 [21 22 23]
 [31 32 33]]


###Perform Subtraction operation

In [7]:
subtraction = H_Vector - V_Vector
print("Subtraction of two vectors is: \n ",subtraction)

Subtraction of two vectors is: 
  [[ -9  -8  -7]
 [-19 -18 -17]
 [-29 -28 -27]]


###Perform Multiplication Operation

In [8]:
multiplication = H_Vector * V_Vector
print("Multiplication of two vectors is: \n ",multiplication)

Multiplication of two vectors is: 
  [[10 20 30]
 [20 40 60]
 [30 60 90]]


###Perfrom division Operation

In [9]:
division = H_Vector / V_Vector
print("Division of two vectors is: \n ",division)

Division of two vectors is: 
  [[0.1        0.2        0.3       ]
 [0.05       0.1        0.15      ]
 [0.03333333 0.06666667 0.1       ]]


###Perform Vector Dot product

In [12]:
vector = np.array([1,2,3])
dot_product = np.dot(vector,vector)
print("Dot product of two vectors is: ",dot_product)

Dot product of two vectors is:  14
