# 1. Create 2X2 Matrix in Python

In [4]:
import numpy as np

Matrix = np.array([[1,2],
                   [5,6]])
Matrix

array([[1, 2],
       [5, 6]])

# 2. Create 3X3 Matrix in Python

In [6]:
import numpy as np

Matrix_3X3 = np.array([[1,2,3],
                      [4,5,6]])
Matrix_3X3

array([[1, 2, 3],
       [4, 5, 6]])

# 3. Perfrom matrix multiplication use `np.dot()`

In [7]:
import numpy as np
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

# 4. Perfrom transpose of a matrix

In [8]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
np.transpose(a)

array([[1, 3],
       [2, 4]])

# 5. Flatten a matrix

In [9]:
import numpy as np
m = np.matrix([[1,2], [3,4]])
m.flatten()
m.flatten('F')

matrix([[1, 3, 2, 4]])

# 6. Indentity Matrix 

In [13]:
import numpy as np

# 3x3 Identity Matrix
I_3x3 = np.eye(3)
print("3x3 Identity Matrix:\n", I_3x3)

# 4x4 Identity Matrix
I_4x4 = np.eye(4)
print("\n4x4 Identity Matrix:\n", I_4x4)

# 3x5 Identity-like Matrix (only diagonal elements are 1)
I_3x5 = np.eye(3, 5)
print("\n3x5 Identity-like Matrix:\n", I_3x5)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4x4 Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

3x5 Identity-like Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
