# Numpy

### Importing the package named **Numpy**

In [1]:
import numpy as np

- Create a variable called **my_list**
- It is a friendly datatype as it allows **CRED** operations

In [2]:
my_list = [1,2,3,4]

In [4]:
type(my_list)

list

In [3]:
my_array = np.array(my_list)

In [5]:
type(my_array)

numpy.ndarray

### Numpy Array


In [6]:
my_matrix = [[1,2,3],[4,5,6]]
my_matrix

[[1, 2, 3], [4, 5, 6]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6]])

- `arange`: genarate sequences

In [9]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

- `np.zeros()`: Create array with 0 element

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

- `np.ones()`: Create array with 1 element

In [12]:
np.ones(30)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

- `linspace`: Genarate equidistance values with a given range

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

- `np.eye`: Indentity matrix

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- `np.rand`: Random value

In [21]:
np.random.rand(5)

array([0.62175139, 0.54085203, 0.91677158, 0.32885011, 0.57728518])

In [28]:
np.random.rand(10,10)

array([[0.28911425, 0.77611194, 0.41651263, 0.08338375, 0.57372216,
        0.95467435, 0.5401532 , 0.8054069 , 0.02983287, 0.72398618],
       [0.61568779, 0.67722401, 0.02523021, 0.99065203, 0.64631301,
        0.75976207, 0.37110038, 0.66659928, 0.79064088, 0.36753015],
       [0.47903422, 0.60984929, 0.09465635, 0.51205809, 0.86640514,
        0.85095626, 0.29584369, 0.24114973, 0.85327741, 0.41692139],
       [0.27389618, 0.34043329, 0.06048126, 0.34899609, 0.09481386,
        0.04363785, 0.02539827, 0.29389889, 0.15959766, 0.33270931],
       [0.5054522 , 0.69409639, 0.39984443, 0.58602177, 0.94185688,
        0.83084355, 0.53925973, 0.42474406, 0.30659145, 0.3236329 ],
       [0.27989347, 0.54887497, 0.90149273, 0.94562563, 0.31879114,
        0.47261643, 0.83291675, 0.23112638, 0.26360389, 0.98829085],
       [0.18792139, 0.88823718, 0.65389848, 0.55953845, 0.67464243,
        0.62078658, 0.24718031, 0.06911145, 0.8877229 , 0.07175245],
       [0.45870617, 0.50107656, 0.5974702

- `np.randint`: Random Integer

In [25]:
np.random.randint(1,100)

35

In [26]:
np.random.randint(1,100,50)

array([18, 48, 32, 77,  6, 93, 40,  8, 65, 26, 89,  7, 31, 36, 20, 64, 42,
       54, 44, 28, 89, 40, 50, 23,  6, 48, 87, 73, 93, 18, 67, 59, 73, 34,
       48,  3,  2, 48, 87, 22, 55, 38,  6, 25, 77, 48, 79, 57, 83,  9])

- `np.reshape`: Reshape Array

In [33]:
array = np.arange(25)

In [34]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
type(array)

numpy.ndarray

In [36]:
array.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

- Max Min, Arg Max, Arg Min

In [37]:
l = np.random.randint(1,100,30)

In [38]:
l

array([78, 24, 56, 31, 49,  3, 49, 26, 84, 73, 47, 46, 88, 66, 28, 53, 13,
       47, 70, 53, 66, 86, 56, 59, 36, 52, 39, 80, 47, 84])

In [39]:
len(l)

30

In [40]:
l.max()

np.int64(88)

In [41]:
l.min()

np.int64(3)

In [42]:
l.argmax() # returns Position of Max value

np.int64(12)

In [43]:
l.argmin() # returns Position of min value

np.int64(5)

- `np.shape`: Checks for shape

In [45]:
np.shape(array)

(25,)

In [46]:
s = array.reshape(5,5)

In [47]:
s

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
np.shape(s)

(5, 5)

- `np.dtype`: Datatype check

In [52]:
s.dtype

dtype('int64')

In [53]:
l1 = np.arange(5)
l2 = np.arange(5)

`np.concat`: Concat two array

In [54]:
np.concat((l1,l2))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

# Task

In [56]:
l = np.zeros((5,5))

In [57]:
l

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [72]:
for i in range(len(l)):
    if i == 0 or i == 3:
        l[i] = 1.0
    elif i == 1 or i == 4:
        l[i] = 0.0
    elif i == 2:
        l[i] = np.random.randint(1, 100, len(l[i]))

In [73]:
l

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.],
       [33., 78., 79., 66., 32.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.,  0.]])