# **Numeric Python**

Before deep diving to the `Numpy` we first have to know why `Numpy`, Lets try to know it with a code.

In [ ]:
import time

n = 10000

m1 = [e for e in range(n) for i in range(n)]
m2 = [e for e in range(n) for i in range(n)]
start = time.time()

for i in range(n):
  for j in range(n):
     m1[i*j] + m2[i*j]

end = time.time()
print(end - start,)

41.88540315628052 seconds


Did you see how long it takes to calculate now I am going to use Numpy array to do the same.

Importing the Library using `import` keyword

In [2]:
import numpy as np

In [ ]:
import time

n = 10000

m1 = [e for e in range(n) for i in range(n)]
m2 = [e for e in range(n) for i in range(n)]

start = time.time()

# Changing the type of m1 & m2

m1 = np.array(m1)
m2 = np.array(m2)

# You don't need use Loop to add Numpy array

m1+m2

end = time.time()
print(end - start, "seconds")

8.098480463027954 seconds


See the change thats why we use numpy rather that traditional list in python. It gives use more efficiency in handeling large amount of data.

Before going to the `array` we are quickly reviceing the `list` cocept in python

### **Python List**

Making a list

In [ ]:
l1 = list() # Making a Object of List class
l1 # It made me a empty list

[]

Alternate way

In [ ]:
l1 = [] # Simply used third brackets
l1 # It made me a empty list

[]

Checking the type with `type()`

In [ ]:
type(l1)

list

Checking Length of a list using `len()`

In [ ]:
len(l1)

0

Inserting same values

In [ ]:
l1 = [1,2,3]
l1

[1, 2, 3]

In [ ]:
l2 = ['Tapabrata','Chowdhury']
l2

['Tapabrata', 'Chowdhury']

Inserting diffrent datatype values

In [ ]:
l3 = [1,'Tapabrata',5.66,True,3+4j]
l3

[1, 'Tapabrata', 5.66, True, (3+4j)]

Inserting list in a list

In [ ]:
l4 = [[1,2,3],[5.22,'Tapabrata',False],[3+5j,3,True,'Chowdhury']]
l4

[[1, 2, 3], [5.22, 'Tapabrata', False], [(3+5j), 3, True, 'Chowdhury']]

Accessing list via index

In [ ]:
l1[1]

2

In [ ]:
l2[2] # Means if we try to access a which is out of his indices it will throw error

IndexError: list index out of range

In [ ]:
l4[0]

[1, 2, 3]

In [ ]:
l4[0][0] # That means go to the first list and in that list go to the first value of first inner list

1

In [ ]:
l4[1][2]

False

As list is itterable thing so we can use `for` loop

In [ ]:
for i in l3:
  print(i)

1
Tapabrata
5.66
True
(3+4j)


We can insert new values in list using `appened()`

In [ ]:
l3.append('New Value')
l3

[1, 'Tapabrata', 5.66, True, (3+4j), 'New Value']

Inserting at spacific location

In [ ]:
l4.insert(1,'New Value')
l4

[[1, 2, 3],
 'New Value',
 [5.22, 'Tapabrata', False],
 [(3+5j), 3, True, 'Chowdhury']]

## **Python Array**

In [ ]:
import array as ar

Unlike `list()` Inline code python stores homogenious data and you have to mension the dtype first before inserting, it only supports one dimention arrays

In [ ]:
arr = ar.array('i',[1,2,3,4,5]) # 'i' Refers as integer datatype
arr

array('i', [1, 2, 3, 4, 5])

Accessing members using indexes

In [ ]:
arr[0]

1

In [ ]:
arr[3]

4

Using negetive indexes

In [ ]:
arr[-2]

4

In [ ]:
arr[-1]

5

Inserting values

In [ ]:
arr.insert(3,0)
arr

array('i', [1, 2, 3, 0, 4, 5])

In [ ]:
arr.append(15)
arr

array('i', [1, 2, 3, 0, 4, 5, 15])

Deleting values using `del ` keyword

In [ ]:
del arr[3]
arr

array('i', [1, 2, 3, 4, 5, 15])

Using `pop()`

In [ ]:
arr.pop()
arr

array('i', [1, 2, 3, 4, 5])

In [ ]:
arr.pop(0)
arr

array('i', [2, 3, 4, 5])

Using `remove()` insted of giving index we have to give value

In [ ]:
arr.remove(3) # This is value not Index
arr

array('i', [2, 4, 5])

Printing only values with `*` Keyword

In [ ]:
print(*arr)

2 4 5


### **Slicing**

We do slicing just as list with `[:]` this and `[::]` this,

In [ ]:
arr2 = ar.array('i',[1,2,3,4,5,6,7,8,9,10])
arr2

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [ ]:
arr2[::]

array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

- One thing is that after that single colon if you the value `x` then the slicing will go to `x-1`

In [ ]:
arr2[1:3] # It will go upto index 2 [3-1]

array('i', [2, 3])

In [ ]:
arr2[1:6:2] # Start from 1 end in 5 and step every 2 numbers

array('i', [2, 4, 6])

- **Negetive Slicing**

In [ ]:
arr2[::-1] # Reversing the array

array('i', [10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
arr2[-4:-1] # Accessing elements from index -4 to -2

array('i', [7, 8, 9])

In [ ]:
arr2[-5:] # Accessing elements from index -5 to the end

array('i', [6, 7, 8, 9, 10])

In [ ]:
arr2[:-2] # Accessing elements from the beginning to index -3

array('i', [1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr2[-4:-1:2] # Accessing elements from index -4 to -2 with a step of 2

array('i', [7, 9])

# **Numpy Basics**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [ ]:
import numpy as np

In [ ]:
ndarray = np.array([1,2,3,4,5])
ndarray

array([1, 2, 3, 4, 5])

In the array we have a limitaion that we can't input more than 1-D Array, But here we can input N-dimension array also it is homogenoous in type.

In [ ]:
type(ndarray)

numpy.ndarray

## **Array Dimensions**

Now we are going to make multiple dimension arrays.

Zero Dimension Array

In [ ]:
ndarray0 = np.array(1) # Contains only one element called Zero dimensional array
ndarray0

array(1)

We will also use `ndim` attribute to calculate it's dimension.

In [ ]:
ndarray0.ndim # Returns the dimension number in this case it is Zero

0

One dimensional array

In [ ]:
ndarray1 = np.array([1,2,3,4,5]) # Contains a list elements called One dimensional array
ndarray1

array([1, 2, 3, 4, 5])

In [ ]:
ndarray1.ndim

1

Two dimensional Array

In [ ]:
ndarray2 = np.array([[1, 2, 3], [4, 5, 6]]) # As it contains two lists of values thats why it is Two dimensional array
ndarray2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
ndarray2.ndim

2

**Homoginity Test**

We know that if we have to put the values with same dtype, Lets test it with some experiment.

In [ ]:
a = np.array([[1,2,3],['4','5','6']]) # We are trying to create a array with one list full of integers and one with full of Strings
a

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U21')

Now if we closely It converted all numbers in Strings to maintain Homoginity

Lets do another test.

In [ ]:
a = np.array([[1,2,3],[4,5,6,7]])
a

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

Now you cann see the error that tells *'inhomogeneous shape after 1 dimensions'*

In [ ]:
a = np.array([[1,2,3],[4,6.55,7.55]])
a

array([[1.  , 2.  , 3.  ],
       [4.  , 6.55, 7.55]])

Same as the previous it converts all the numbers in to floating point values.

Three Diensional Array

In [ ]:
ndarray3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # As it contains two two dimensional lists of values or we can say it matrices thats why it is Three dimensional array
ndarray3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
ndarray3.ndim

3

We can create as much dimensional as posssible but for human mind it seems to be difficult to visualize more than 3-D

# **Array Attributes**

- `dtype` : Need to indentify the datatype of a array. [Click to know more about dtype](https:/numpy.org/doc/2.1/reference/arrays.dtypes.html)

In [ ]:
x = np.array([1,2,3,4])
x.dtype

dtype('int64')

We can change data types also usng this attribute while declaring array

In [ ]:
y = np.array([2,5,8], dtype=np.float32)
y

array([2., 5., 8.], dtype=float32)

we can also do it as

In [ ]:
z = np.array([2,5,8], dtype='f4')
z

array([2., 5., 8.], dtype=float32)

In [ ]:
m = np.array([2,3,6,9,10],dtype='S')
m

array([b'2', b'3', b'6', b'9', b'10'], dtype='|S2')

- `shape`: Returns the number of rows and columns

In [ ]:
arr1D = np.array([1,2,3])
print("There are:",arr1D.shape,"columns in the the array")
arr2D = np.array([[1,2,3],[4,5,6]])
print("There are:",arr2D.shape,"rows & columns in the the array")
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("There are:",arr3D.shape,"rows and under that there are rows & columns in the the array")

There are: (3,) columns in the the array
There are: (2, 3) rows & columns in the the array
There are: (2, 2, 3) rows and under that there are rows & columns in the the array


- `size`: Returns the number of elements

In [ ]:
arr_size1D = np.array([1,2,3,4,5])
arr_size1D.size

5

In [ ]:
arr_size2D = np.array([[1,2,3,4,5],
                       [5,6,9,9,2]])
arr_size2D.size

10

- `ndim`: Returns the diamension

In [ ]:
arr1D.ndim

1

In [ ]:
arr2D.ndim

2

In [ ]:
arr3D.ndim

3

- `astype`: Helps to convert the datatype

In [ ]:
arr_type1 = np.array([1,2,3]) # Int
arr_type2 = np.array([1.2,2.5,3.33]) # Float
arr_type3 = np.array(['1','2','3']) # String

In [ ]:
arr_type1.astype(float).dtype

dtype('float64')

In [ ]:
arr_type2.astype(int).dtype

dtype('int64')

In [ ]:
arr_type3.astype(float).dtype

dtype('float64')

- Now we are going to perfrom some of the mathematical operation
  - `+`: Adds
  - `-`: Subtract
  - `*`: Multiply
  - `/`: Devide
  - `**`: Power
  - `%`: Modulus
  - `//`: Floar Division

In [ ]:
operand_1  = np.array([[1,2,3,4,5],
                       [5,8,9,3,1]])

operand_2  = np.array([[1,2,3,4,5],
                       [5,8,9,3,1]])

print("Addition:\n",operand_1 + operand_2)
print("Subtraction:\n",operand_1 - operand_2)
print("Multiplication:\n",operand_1 * operand_2)
print("Division:\n",operand_1 / operand_2)
print("Power:\n",operand_1 ** operand_2)
print("Modulus:\n",operand_1 % operand_2)
print("Floar Division:\n", operand_1 // operand_2)

Addition:
 [[ 2  4  6  8 10]
 [10 16 18  6  2]]
Subtraction:
 [[0 0 0 0 0]
 [0 0 0 0 0]]
Multiplication:
 [[ 1  4  9 16 25]
 [25 64 81  9  1]]
Division:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Power:
 [[        1         4        27       256      3125]
 [     3125  16777216 387420489        27         1]]
Modulus:
 [[0 0 0 0 0]
 [0 0 0 0 0]]
Floar Division:
 [[1 1 1 1 1]
 [1 1 1 1 1]]


- Now we are looking on some aggregaton function

In [ ]:
agg = np.array([1,5,8,6,3,2,5])
print(np.sum(agg))  # This is called sum
print(np.min(agg))  # This is called minimum number
print(np.max(agg))  # This is called max number
print(np.mean(agg)) # This is called
print(np.std(agg))  # This is called standard daviation
print(np.var(agg))  # This is called varience

30
1
8
4.285714285714286
2.2497165354319457
5.061224489795918


- Apart from that we some addtional sequence genarating methods

In [ ]:
np.ones((2,5)) # Create a array with number 1, we have to give rows & columns if we want to make multidimensional arrays

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((5,10)) # Create a with number 0, we have to give rows & columns if we want to make multidimensional arrays

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.full((3,5),4) # Make an array of our own preffered number (size,number)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [ ]:
np.arange(1,20,5) # Genarate a sequence of number (start,stop,step)

array([ 1,  6, 11, 16])

In [ ]:
np.eye(5,5) # Create diagonal matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# **Indexing and Slicing**

- Accessing a specific element. It follows 0 based indexing

In [ ]:
arr = np.array([5,8,9,6,1,4])
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])
print(arr[5])
print("-ve indexing:")
print(arr[-1])
print(arr[-2])
print(arr[-3])
print(arr[-4])
print(arr[-5])
print(arr[-6])

5
8
9
6
1
4
-ve indexing:
4
1
6
9
8
5


- Slicing: Extracting sub array from an array

In [ ]:
arr_slice = np.array([1,5,6,2,8,10])
print(arr_slice[0:3])
print(arr_slice[1:4])
print(arr_slice[::2])
print(arr_slice[::-1])
# -ve slice
print(arr_slice[-3:-1])
print(arr_slice[-4:-1])
print(arr_slice[-4:-1:2])
print(arr_slice[-1:-4:-1])

[1 5 6]
[5 6 2]
[1 6 8]
[10  8  2  6  5  1]
[2 8]
[6 2 8]
[6 8]
[10  8  2]


- Fancy Indexing: Selecting multiple index at once

In [ ]:
arr_fancy = np.array([1,5,6,2,8,10])
# Makes a copy and then print that so that real data does effect
print(arr_fancy[[0,2,4]])
print(arr_fancy[[1,3,5]])
print(arr_fancy[[-1,-2,-3]])
print(arr_fancy[[-4,-5,-6]])

[1 6 8]
[ 5  2 10]
[10  8  2]
[6 5 1]


- Boolean masting or Filtering: Slicing the data based on some condition

In [ ]:
arr_bool = np.array([10,20,30,40,50,60])
print(arr[arr_bool > 25])

[30 40 50 60]


# **Reshaping and Manupulating array**

- Reshape possible if dimention match

In [ ]:
arr_reshape = np.array([1,5,6,2,8,10])
print(arr_reshape.reshape(3,2))
print(arr_reshape.reshape(2,3))
print(arr_reshape.reshape(-1,6))
print(arr_reshape.reshape(-6,1))

[[ 1  5]
 [ 6  2]
 [ 8 10]]
[[ 1  5  6]
 [ 2  8 10]]
[[ 1  5  6  2  8 10]]
[[ 1]
 [ 5]
 [ 6]
 [ 2]
 [ 8]
 [10]]


### **Flatterning array**
- We have two methods `ravel()` and `flatten()` first one creates view and second one creates copy. Both convert multidimentional data to 1D

In [ ]:
arr_reshape2D = np.array([[5,8,2],[1,5,9]])

In [ ]:
arr_reshape2D.ravel() # There is no diffrence in output but it chages real one

array([5, 8, 2, 1, 5, 9])

In [ ]:
arr_reshape2D.flatten() # There is no diffrence in output but it doesn't change the real data

array([5, 8, 2, 1, 5, 9])

# **Array Modification**

`insert`: Insert new element in an existing array

In [ ]:
arr_mod1D = np.array([1,2,3,4,5,6,7,8,9,10])

print(np.insert(arr_mod1D,5,60,axis=None))

[ 1  2  3  4  5 60  6  7  8  9 10]


In [ ]:
arr_mod2D = np.array([[1,2],[3,4]])
print(arr_mod2D,end='\n\n')
print(np.insert(arr_mod2D,1,[3,9],axis=0),end='\n\n')
print(np.insert(arr_mod2D,1,[3,9],axis=1),end='\n\n')
print(np.insert(arr_mod2D,1,[3,9],axis=None),end='\n\n')

[[1 2]
 [3 4]]

[[1 2]
 [3 9]
 [3 4]]

[[1 3 2]
 [3 9 4]]

[1 3 9 2 3 4]



`appened`: Add element at last position

In [ ]:
arr_app = np.array([1,2,3])
print(np.append(arr_app,4))

[1 2 3 4]


`concatinate`: Merge arrays

In [ ]:
arr_con1 = np.array([[1, 2], [3, 4]])
arr_con2 = np.array([[5, 6]])
print(np.concatenate((arr_con1,arr_con2), axis=0))
print(np.concatenate((arr_con1, arr_con2.T), axis=1)) # .T means Transpose converting the second array to it's transpose version
print(np.concatenate((arr_con1,arr_con2), axis=None))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]


`delete`: For deleting array values

In [ ]:
arr_del1D = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.delete(arr_del1D,5),end='\n\n')
arr_del2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.delete(arr_del2D,1,axis=0),end='\n\n')
print(np.delete(arr_del2D,1,axis=1),end='\n\n')
print(np.delete(arr_del2D,1,axis=None))

[ 1  2  3  4  5  7  8  9 10]

[[1 2 3]
 [7 8 9]]

[[1 3]
 [4 6]
 [7 9]]

[1 3 4 5 6 7 8 9]


- Staking:
  - `vstack()`: Vertical Staking
  - `hstack()`: Horizontal Staking

In [ ]:
arr_stack1 = np.array([[1,2,3],[4,8,5]])
print(arr_stack1,end='\n\n')
arr_stack2 = np.array([[6,7,8],[9,10,11]])
print(arr_stack2,end='\n\n')
print(np.vstack((arr_stack1,arr_stack2)),end='\n\n')
print(np.hstack((arr_stack1,arr_stack2)))

[[1 2 3]
 [4 8 5]]

[[ 6  7  8]
 [ 9 10 11]]

[[ 1  2  3]
 [ 4  8  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 1  2  3  6  7  8]
 [ 4  8  5  9 10 11]]


- Splitting: Splits the array
  - `split`: Splits in equal parts
  - `hsplit`: Horizontal spliting proccess
  - `vsplit`: Vertical splitting proccess

In [5]:
arr_split = np.array([10,20,30,40,50,60,70,80,90])
print(np.split(arr_split,3)) # Here 3 means how many parts to be splitted
print(np.split(arr_split,[2,6]))
"""

print(np.split(arr_split,[2,6])): This line demonstrates a more controlled split. The second argument [2,6]
specifies the indices where the array should be split. In this case, it splits the array at index 2 and index 6, resulting in a list of 3 arrays:
        The first array contains elements from index 0 to 1.
        The second array contains elements from index 2 to 5.
        The third array contains elements from index 6 to the end.

"""

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80, 90])]
[array([10, 20]), array([30, 40, 50, 60]), array([70, 80, 90])]


# **Brodcasting and Vectorization**

- Brodcasting is Numpy way where we can perform diffrent mathematical operations **without using Loops**

In [7]:
Stuffs_prize = [100,200,300]
discount = 10
discounted_prize = []
for i in Stuffs_prize:
    discounted_prize.append(i - (i * discount)/100)
discounted_prize # This procces is ok but becomes too slow if we try do that with larger data

[90.0, 180.0, 270.0]

Now let's do that thing withthe help of numpy

In [10]:
Stuffs_prize = np.array([100,200,300])
discount = 10
discounted_prize = np.array(Stuffs_prize - (Stuffs_prize * discount)/100)
discounted_prize # No need loops this is more efficient

array([ 90., 180., 270.])

### Handeling diffrent shapes of array in numpy

- Matching dimensions: If arrays are sames in shape then it can perfrom tasks
- Expanding single element: Perfrom operations of array with single element is possible without thinking about shapes
- Incompatable shapes: Leads to error

- Vectorize 1D to 2D array

In [30]:
A = np.array([[1,2,3],[5,6,9]])
B = np.array([1,8,6])
print(A+B)

[[ 2 10  9]
 [ 6 14 15]]


- Error Code [Incompatable shapes: Leads to error]

In [16]:
C = np.array([[1,2,3],[5,6,9]])
D = np.array([1,8])
print(C+D)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

### Vectorization

In [29]:
import time
# List Comprehension
L = [10,20,30,40,50]
R = [60,70,80,90,100]
start = time.time()

Result = [i+j for i,j in zip(L,R)]
end = time.time()
print(end-start)
Result

0.00014543533325195312


[70, 90, 110, 130, 150]

In [31]:
import time
A = np.array([10,20,30,40,50])
B = np.array([60,70,80,90,100])
start = time.time()
Result = A + B
end = time.time()
print(end-start)
Result

7.557868957519531e-05


array([ 70,  90, 110, 130, 150])

### ⚔️ **Differences at a Glance:**
| Feature           | Broadcasting               | Vectorization              |
|-------------------|----------------------------|----------------------------|
| **Purpose**        | Handle different shapes    | Speed up array operations  |
| **Main Action**    | Expands dimensions         | Removes explicit loops     |
| **Memory Impact**  | No extra memory if broadcasted properly | Minimal memory usage |
| **Error Handling** | Fails if incompatible shapes | Rarely raises errors |
| **Example Operation** | Adding arrays of different shapes | Squaring an array |

In [32]:
import numpy as np

# Array of shape (3, 1)
A = np.array([[1], [2], [3]])

# Array of shape (1, 3)
B = np.array([4, 5, 6])

# Broadcasting happens to make both arrays shape (3, 3)
result = A + B
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [33]:
# Vectorized operation
A = np.array([1, 2, 3, 4, 5])
B = A ** 2  # Element-wise squaring (vectorized)
print(B)

[ 1  4  9 16 25]


# **Handeling Missing Values**

- `np.nan`
- `np.isnan`
- `np.isinf`

In [41]:
e = np.array([1,2,np.nan,4,5])
np.isnan(e)

array([False, False,  True, False, False])

In [43]:
np.nan_to_num(e,nan=500) # Replacing NULL values

array([  1.,   2., 500.,   4.,   5.])

In [48]:
f = np.array([1,np.inf,-np.inf,5,8])

In [49]:
np.isinf(f)

array([False,  True,  True, False, False])

In [50]:
np.nan_to_num(f,posinf=5,neginf=-5)

array([ 1.,  5., -5.,  5.,  8.])